name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - elixir: 1.17.2
            otp: 26.2.5

    steps:
    - uses: actions/checkout@v1
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
        version-type: "strict"
    - name: Cache build artifacts
      uses: actions/cache@v2
      with:
        path: |
          ~/.hex
          ~/.mix
          deps
          _build
          priv/plts
        key: ${{ matrix.otp }}-${{ matrix.elixir }}
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    # https://elixirforum.com/t/github-action-cache-elixir-always-recompiles-dependencies-elixir-1-13-3/45994/12
    - name: Compile Deps
      run: mix loadpaths
    - name: Compile
      run: MIX_ENV=test mix compile --force --warnings-as-errors
    - name: Run Tests
      run: mix test
    - name: Check format
      run: mix format --check-formatted
    - name: Credo
      run: MIX_ENV=test mix credo --strict
#    - name: Dialyzer
#      run: MIX_ENV=test mix dialyzer --halt-exit-status
